/*
 * prem-chat
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<i32>,
    #[serde(rename = "choices")]
    pub choices: Vec<serde_json::Value>,
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<serde_json::Value>,
}

impl ChatCompletionResponse {
    pub fn new(model: String, choices: Vec<serde_json::Value>) -> ChatCompletionResponse {
        ChatCompletionResponse {
            id: None,
            model,
            object: None,
            created: None,
            choices,
            usage: None,
        }
    }
}
